name: ctz
channels:
  - conda-forge
  - nodefaults
dependencies:
  # HyRiver deps
  - setuptools
  - owslib
  - defusedxml
  - requests
  - requests_cache
  - aiohttp
  - chardet
  - aiodns
  - brotlipy
  - nest-asyncio
  - xarray
  - netCDF4
  - geopandas
  - pyproj
  - pyarrow
  - rasterio
  - shapely
  - orjson
  - simplejson
  - lxml
  - dask-core
  - matplotlib-base
  - folium
  - openpyxl

  # HyRiver packages
  - pygeoogc
  - async_retriever
  - pygeohydro

  # Speedups
  - bottleneck
  - pygeos
  - rtree

  # Other third-party deps
  - mapclassify
  - joblib
  - utide
  - xskillscore
  - scipy
  - contextily
  - tqdm
  - pytables
  - jupyterlab_widgets
  - ipywidgets

  - pip
  - pip:
    - aiohttp-client-cache
