name: ctz
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9

  # HyRiver packages
  - pygeoogc
  - async_retriever
  - pygeohydro

  # Speedups
  - bottleneck
  - pygeos

  # Other third-party deps
  - mapclassify
  - joblib
  - utide
  - xskillscore
  - scipy
  - contextily
  - tqdm
  - pytables
  - ipywidgets
