[tool.nbqa.mutate]
isort = 1
black = 1
pyupgrade = 1
flake8 = 0

[tool.nbqa.addopts]
isort = ["-l", "100", "--profile", "black", "--multi-line", "3", "--tc", "--up"]
black = ["-t", "py38", "-l", "100"]
pyupgrade = ["--py37-plus"]
flake8 = ["--ignore", "E203,E402,E501,E731,W503,D107,D105", "--exclude",
"__init__.py,.ipynb_checkpoints", "--max-line-length", "100"]
